import { vibrate } from '../engine/haptics';
import { attachDrag, magnetizeRawDist } from '../engine/drag';
import type { Lang } from '../i18n';

// A 9-row x 4-column letter grid, styled like the game's own tiles — the
// vertical/portrait counterpart of the original 4x9 layout (see git history
// for that version): each COLUMN now belongs to one language and spells
// nearly its whole word at rest, top to bottom. Only 4 of the 9 ROWS are
// draggable (horizontally, one row at a time — same magnetizeRawDist snap
// feel and pixel-based edgeFade wraparound ghost fill as every other board
// in this game). Each drag row supplies exactly one missing letter to
// exactly one column; dragging it to the right horizontal offset (a cyclic
// shift among the 4 columns) delivers that letter and completes that
// column's word, entering that language. This grid's exact cell contents
// were generated by mechanically transposing + reordering the previous
// (verified, shipped) 4x9 grid — see scratch-transpose-lang.mjs in this
// session's history — so the same "each drag row solves exactly one column,
// and only at exactly one shift amount" guarantee still holds by
// construction, just checked again for this shape.
type Cell = { kind: 'char'; text: string; lang: Lang } | { kind: 'filler'; colorIdx: number };

const LANG_COLOR: Record<Lang, string> = {
  en: '#2F9E52',
  fr: '#AD5C82',
  zhHant: '#4C68B0',
  zhHans: '#6B6560',
};
const FILLER_COLORS = [LANG_COLOR.en, LANG_COLOR.fr, LANG_COLOR.zhHant, LANG_COLOR.zhHans];

const ROWS = 9;
const COLS = 4;
const DRAG_ROWS = [1, 2, 7, 8];
const COL_LANG: Lang[] = ['zhHant', 'en', 'fr', 'zhHans'];
const COL_WORD: string[][] = [
  ['繁', '體', '中', '文'],
  ['E', 'N', 'G', 'L', 'I', 'S', 'H'],
  ['F', 'R', 'A', 'N', 'Ç', 'A', 'I', 'S'],
  ['简', '体', '中', '文'],
];
const COL_START = [1, 2, 0, 5];
// The arrow hint's fixed gap position + pointer direction + tint per drag
// row — chosen once here (not derived from the drag's live position) so
// each hint reads as "watch this specific spot," matching the reference
// layout's per-row markers rather than one hint that follows the pointer.
// gapAfter: the column index this row's arrow sits just to the right of
// (gapAfter=k means the slot between column k and k+1); pointLeft: true
// points the arrowhead back at gapAfter (the usual case), false points it
// forward at gapAfter+1 (used only for the rightmost target column, so the
// arrow never has to sit off the board's right edge).
const DRAG_ROW_ARROW: Record<number, { gapAfter: number; pointLeft: boolean; color: string }> = {
  1: { gapAfter: 0, pointLeft: true, color: '#F2B84B' },
  2: { gapAfter: 2, pointLeft: true, color: '#3FB8A6' },
  7: { gapAfter: 1, pointLeft: true, color: '#E8637A' },
  8: { gapAfter: 2, pointLeft: false, color: '#F2D33B' },
};

function ch(text: string, lang: Lang): Cell {
  return { kind: 'char', text, lang };
}
function fc(colorIdx: number): Cell {
  return { kind: 'filler', colorIdx };
}

// Generated by transposing the previous 4x9 grid (image column order
// zhHant/en/fr/zhHans) — see the module comment above.
function buildGrid(): Cell[][] {
  return [
    [fc(3), fc(2), ch('F', 'fr'), fc(0)],
    [fc(0), ch('繁', 'zhHant'), ch('R', 'fr'), fc(1)],
    [ch('體', 'zhHant'), ch('E', 'en'), fc(3), ch('A', 'fr')],
    [ch('中', 'zhHant'), ch('N', 'en'), ch('N', 'fr'), fc(3)],
    [ch('文', 'zhHant'), ch('G', 'en'), ch('Ç', 'fr'), fc(0)],
    [fc(0), ch('L', 'en'), ch('A', 'fr'), ch('简', 'zhHans')],
    [fc(1), ch('I', 'en'), ch('I', 'fr'), ch('体', 'zhHans')],
    [fc(2), fc(1), ch('S', 'fr'), ch('中', 'zhHans')],
    [ch('文', 'zhHans'), ch('H', 'en'), fc(1), fc(0)],
  ];
}

export function renderLanguageSelect(container: HTMLElement, onSelect: (lang: Lang) => void) {
  container.innerHTML = `
    <div class="app lang-select-page lang-select-page--vertical">
      <h1 class="lang-title">Slides</h1>
      <p class="lang-instructions">拖动带箭头的行，拼出你的语言</p>
      <div class="lang-board-wrap" id="langBoardWrap">
        <div class="lang-board lang-board--vertical" id="langBoard"></div>
      </div>
    </div>
  `;
  const boardOrNull = container.querySelector<HTMLElement>('#langBoard');
  const boardWrapOrNull = container.querySelector<HTMLElement>('#langBoardWrap');
  if (!boardOrNull || !boardWrapOrNull) throw new Error('languageSelect: board not found');
  const board: HTMLElement = boardOrNull;
  const boardWrap: HTMLElement = boardWrapOrNull;

  const grid = buildGrid();
  let settled = false;

  const colEls: HTMLElement[] = [];
  const cellEls: HTMLElement[][] = Array.from({ length: ROWS }, () => []);

  function paintCell(el: HTMLElement, cell: Cell) {
    if (cell.kind === 'filler') {
      el.style.background = FILLER_COLORS[cell.colorIdx];
      el.textContent = '';
    } else {
      el.style.background = LANG_COLOR[cell.lang];
      el.textContent = cell.text;
    }
  }

  for (let c = 0; c < COLS; c++) {
    const colEl = document.createElement('div');
    colEl.className = 'lang-col lang-col--vertical';
    for (let r = 0; r < ROWS; r++) {
      const cellEl = document.createElement('div');
      cellEl.className = 'lang-cell';
      paintCell(cellEl, grid[r][c]);
      colEl.appendChild(cellEl);
      cellEls[r][c] = cellEl;
    }
    board.appendChild(colEl);
    colEls[c] = colEl;
  }

  // Per-row hit target + arrow hint: separate absolutely-positioned overlay
  // elements, not extra in-flow flex children mixed in with the real cells —
  // an earlier horizontal version of this grid (the arrow-above-column
  // design) put the arrow as a real flex sibling *inside* the draggable
  // column, which silently shifted every cell's effective offset within
  // that column and threw off the ghost/wraparound fill math to look like
  // it was "routing around" the arrow. Keeping the hint entirely outside
  // the cell layout avoids that bug by construction.
  const rowHitEls: Record<number, HTMLElement> = {};
  const arrowEls: Record<number, HTMLElement> = {};
  for (const dr of DRAG_ROWS) {
    const hit = document.createElement('div');
    hit.className = 'lang-row-hit';
    board.appendChild(hit);
    rowHitEls[dr] = hit;

    const arrow = document.createElement('div');
    arrow.className = 'lang-row-arrow';
    const cfg = DRAG_ROW_ARROW[dr];
    arrow.style.color = cfg.color;
    arrow.innerHTML =
      '<svg viewBox="0 0 24 24" width="16" height="16"><path d="M15 5l-7 7 7 7" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>';
    if (!cfg.pointLeft) arrow.classList.add('lang-row-arrow--flip');
    boardWrap.appendChild(arrow);
    arrowEls[dr] = arrow;
  }

  function layoutOverlays() {
    const boardRect = board.getBoundingClientRect();
    const wrapRect = boardWrap.getBoundingClientRect();
    for (const dr of DRAG_ROWS) {
      const cellRect = cellEls[dr][0].getBoundingClientRect();
      const hit = rowHitEls[dr];
      hit.style.left = '0px';
      hit.style.width = boardRect.width + 'px';
      hit.style.top = cellRect.top - boardRect.top + 'px';
      hit.style.height = cellRect.height + 'px';

      const cfg = DRAG_ROW_ARROW[dr];
      const gapCellL = cellEls[dr][cfg.gapAfter].getBoundingClientRect();
      const gapCellR = cellEls[dr][cfg.gapAfter + 1].getBoundingClientRect();
      const gapCenterX = (gapCellL.right + gapCellR.left) / 2;
      const cy = gapCellL.top + gapCellL.height / 2;
      const arrow = arrowEls[dr];
      // Positioned relative to boardWrap (its actual offsetParent), not board.
      arrow.style.left = gapCenterX - wrapRect.left + 'px';
      arrow.style.top = cy - wrapRect.top + 'px';
    }
  }

  // Same pixel-based edge fade every other board's drag preview uses: a
  // ghost fully outside [low, high] is invisible, one just past the edge
  // ramps in over `range` instead of popping in at full ghost opacity.
  function edgeFade(x: number, low: number, high: number, range: number): number {
    const overshoot = x < low ? low - x : x > high ? x - high : 0;
    return Math.max(0, 1 - overshoot / range);
  }

  function stepFor(r: number): number {
    const first = cellEls[r][0].getBoundingClientRect();
    const second = cellEls[r][1].getBoundingClientRect();
    return second.left - first.left;
  }

  for (const r of DRAG_ROWS) {
    const hit = rowHitEls[r];
    let dx = 0;

    function clearGhosts() {
      for (let c = 0; c < COLS; c++) {
        const parent = cellEls[r][c].parentElement!;
        parent.querySelectorAll(`.lang-cell.ghost[data-row="${r}"]`).forEach((g) => g.remove());
      }
    }

    function renderDragPreview() {
      const step = stepFor(r);
      const cellW = cellEls[r][0].getBoundingClientRect().width;
      const span = step * COLS;
      const magDx = magnetizeRawDist(dx / step) * step;

      for (let c = 0; c < COLS; c++) cellEls[r][c].style.transform = `translateX(${magDx}px)`;

      clearGhosts();
      const fadeRange = step * 0.4;
      for (let k = -1; k <= 1; k++) {
        if (k === 0) continue;
        for (let c = 0; c < COLS; c++) {
          const baseLeft = c * step;
          const x = baseLeft + magDx + k * span;
          const fade = edgeFade(x, -step, span - step, fadeRange);
          if (fade <= 0) continue;
          const cellRect = cellEls[r][c].getBoundingClientRect();
          const colRect = cellEls[r][c].parentElement!.getBoundingClientRect();
          const ghost = document.createElement('div');
          ghost.className = 'lang-cell ghost';
          ghost.dataset.row = String(r);
          paintCell(ghost, grid[r][c]);
          ghost.style.position = 'absolute';
          ghost.style.left = cellRect.left - colRect.left + 'px';
          ghost.style.top = '0';
          ghost.style.width = cellW + 'px';
          ghost.style.height = cellRect.height + 'px';
          ghost.style.transform = `translateX(${x - baseLeft}px)`;
          ghost.style.opacity = String(0.55 * fade);
          ghost.style.pointerEvents = 'none';
          cellEls[r][c].parentElement!.appendChild(ghost);
        }
      }
    }

    function applyShift() {
      const step = stepFor(r);
      const shift = Math.round(dx / step);
      clearGhosts();
      for (let c = 0; c < COLS; c++) cellEls[r][c].style.transform = '';
      if (shift === 0) return;
      const n = COLS;
      const rowVals = grid[r].slice();
      const shifted = rowVals.map((_, i) => rowVals[(((i - shift) % n) + n) % n]);
      for (let c = 0; c < COLS; c++) {
        grid[r][c] = shifted[c];
        paintCell(cellEls[r][c], grid[r][c]);
      }
      vibrate(10);
      checkCompletion();
    }

    attachDrag(hit, {
      isActive: () => !settled,
      onStart() {
        dx = 0;
        hit.classList.add('lang-row-hit--active');
      },
      onDrag(ddx) {
        dx = ddx;
        renderDragPreview();
      },
      onEnd(ddx) {
        dx = ddx;
        applyShift();
        hit.classList.remove('lang-row-hit--active');
      },
    });
  }

  function checkCompletion() {
    for (let c = 0; c < COLS; c++) {
      const word = COL_WORD[c];
      const start = COL_START[c];
      let ok = true;
      for (let i = 0; i < word.length; i++) {
        const cell = grid[start + i][c];
        if (cell.kind !== 'char' || cell.text !== word[i]) {
          ok = false;
          break;
        }
      }
      if (!ok) continue;
      settled = true;
      vibrate(24);
      const solvedEls: HTMLElement[] = [];
      for (let i = 0; i < word.length; i++) {
        const el = cellEls[start + i][c];
        el.classList.add('lang-cell--solving');
        solvedEls.push(el);
      }
      // A real score-style pulse (scale + glow, a couple of beats) plays out
      // before handing off — completing a word should read as a small win,
      // not an instant cut to the next screen.
      setTimeout(() => {
        for (const el of solvedEls) {
          el.classList.remove('lang-cell--solving');
          el.classList.add('lang-cell--solved');
        }
      }, 640);
      setTimeout(() => onSelect(COL_LANG[c]), 900);
      return;
    }
  }

  layoutOverlays();
  const onResize = () => layoutOverlays();
  window.addEventListener('resize', onResize);
}
