import { vibrate } from '../engine/haptics';
import { attachDrag, magnetizeRawDist } from '../engine/drag';
import type { Lang } from '../i18n';

// A 9-row x 4-column letter grid, styled like the game's own tiles — the
// vertical/portrait counterpart of the original 4x9 layout (see git history
// for that version): each COLUMN now belongs to one language and spells
// nearly its whole word at rest, top to bottom. Only 4 of the 9 ROWS are
// draggable (horizontally, one row at a time — same magnetizeRawDist snap
// feel and pixel-based edgeFade wraparound ghost fill as every other board
// in this game). Each drag row supplies exactly one missing letter to
// exactly one column; dragging it to the right horizontal offset (a cyclic
// shift among the 4 columns) delivers that letter and completes that
// column's word, entering that language. This grid's exact cell contents
// were generated by mechanically transposing + reordering the previous
// (verified, shipped) 4x9 grid — see scratch-transpose-lang.mjs in this
// session's history — so the same "each drag row solves exactly one column,
// and only at exactly one shift amount" guarantee still holds by
// construction, just checked again for this shape. Re-verified after the
// reference-image restyle: no word is complete at rest, and each of the four
// rows completes exactly one language at a shift of exactly one slot LEFT —
// which is why every arrow hint below points the same way.
type Cell = { kind: 'char'; text: string; lang: Lang } | { kind: 'filler'; colorIdx: number };

// The reference image's exact 5-colour set. Four of them double as the
// per-language tints below; the brick red belongs to no language and only
// ever shows up on letterless filler tiles, so a red tile can never be
// mistaken for "part of a word I'm assembling".
const PALETTE = {
  green: '#2E8B32',
  brick: '#B0432A',
  gray: '#B4B4B4',
  orange: '#E9A53C',
  blue: '#4A6FC4',
} as const;

const LANG_COLOR: Record<Lang, string> = {
  zhHant: PALETTE.orange,
  en: PALETTE.green,
  fr: PALETTE.blue,
  zhHans: PALETTE.gray,
};
// Indexed by buildGrid's fc() calls — kept in this fixed order (green,
// brick, gray, orange) so those indices read straight off the reference
// image. Blue is deliberately absent: the image never tints a filler blue.
const FILLER_COLORS = [PALETTE.green, PALETTE.brick, PALETTE.gray, PALETTE.orange];

const ROWS = 9;
const COLS = 4;
const DRAG_ROWS = [1, 2, 7, 8];
const COL_LANG: Lang[] = ['zhHant', 'en', 'fr', 'zhHans'];
const COL_WORD: string[][] = [
  ['繁', '體', '中', '文'],
  ['E', 'N', 'G', 'L', 'I', 'S', 'H'],
  ['F', 'R', 'A', 'N', 'Ç', 'A', 'I', 'S'],
  ['简', '体', '中', '文'],
];
const COL_START = [1, 2, 0, 5];
// Where each drag row's in-grid arrow sits, as the gap it straddles:
// gapAfter=k is the slot between column k and column k+1, and gapAfter=-1
// is the slot just outside column 0's left edge. Every row shifts LEFT, so
// every arrow points left — for rows 1/2/7 it sits right where the
// travelling letter is about to land, and for row 8 (whose letter leaves
// column 0 and wraps around to column 3) it sits at the board's left edge,
// showing the letter heading off that side rather than pointing at a gap
// the letter never crosses.
const DRAG_ROW_ARROW_GAP: Record<number, number> = { 1: 0, 2: 2, 7: 1, 8: -1 };

// A white arrowhead trailing two amber dashes — white reads against all
// five tile colours (the amber tail would vanish on an orange tile, so the
// head, not the tail, carries the legibility), and a drop-shadow in the CSS
// keeps it off the lighter grays.
const GAP_ARROW_SVG =
  '<svg viewBox="0 0 34 14" aria-hidden="true">' +
  '<path d="M1 7 L11.5 1.2 L11.5 12.8 Z" fill="#FFFFFF"/>' +
  '<path d="M15 7 H21.5" stroke="#E9A53C" stroke-width="3" stroke-linecap="round"/>' +
  '<path d="M26.5 7 H32.8" stroke="#E9A53C" stroke-width="3" stroke-linecap="round"/>' +
  '</svg>';
// The board-edge marker: a plain double chevron in page ink, sitting on the
// page background rather than on a tile, so it takes no white outline.
const EDGE_CHEVRON_SVG =
  '<svg viewBox="0 0 24 16" aria-hidden="true">' +
  '<path d="M10 2.6 L4 8 L10 13.4 M20 2.6 L14 8 L20 13.4" fill="none" stroke="currentColor" ' +
  'stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/>' +
  '</svg>';

function ch(text: string, lang: Lang): Cell {
  return { kind: 'char', text, lang };
}
function fc(colorIdx: number): Cell {
  return { kind: 'filler', colorIdx };
}

// Cell-for-cell from the reference image: same letter placement the shipped
// grid already used (its "one drag row solves exactly one column, at exactly
// one shift" property is unchanged), with every tile's tint now taken
// straight off that image.
//
// Note each travelling letter is tinted by the language it is heading FOR,
// not the column it currently sits in — 繁 waits in English's column in
// zhHant orange, A waits in 简体中文's column in French blue, S waits in
// French's column in English green, 文 waits in 繁體中文's column in
// 简体中文 gray. That is what makes the four movable letters legible as
// "outsiders" at a glance, and it costs nothing: a cell's `lang` tag only
// picks its colour, while checkCompletion below matches on `text` alone.
function buildGrid(): Cell[][] {
  return [
    [fc(1), fc(2), ch('F', 'fr'), fc(1)],
    [fc(0), ch('繁', 'zhHant'), ch('R', 'fr'), fc(0)],
    [ch('體', 'zhHant'), ch('E', 'en'), fc(3), ch('A', 'fr')],
    [ch('中', 'zhHant'), ch('N', 'en'), ch('N', 'fr'), fc(1)],
    [ch('文', 'zhHant'), ch('G', 'en'), ch('Ç', 'fr'), fc(2)],
    [fc(0), ch('L', 'en'), ch('A', 'fr'), ch('简', 'zhHans')],
    [fc(1), ch('I', 'en'), ch('I', 'fr'), ch('体', 'zhHans')],
    [fc(3), fc(2), ch('S', 'en'), ch('中', 'zhHans')],
    [ch('文', 'zhHans'), ch('H', 'en'), fc(3), fc(0)],
  ];
}

export function renderLanguageSelect(container: HTMLElement, onSelect: (lang: Lang) => void) {
  // Held only while this screen is mounted; teardown() below drops it again
  // before handing off, so every later screen scrolls normally.
  document.documentElement.classList.add('lang-locked');
  container.innerHTML = `
    <div class="app lang-select-page lang-select-page--vertical">
      <h1 class="lang-title">Slides</h1>
      <div class="lang-board-wrap" id="langBoardWrap">
        <div class="lang-board lang-board--vertical" id="langBoard"></div>
      </div>
    </div>
  `;
  const boardOrNull = container.querySelector<HTMLElement>('#langBoard');
  const boardWrapOrNull = container.querySelector<HTMLElement>('#langBoardWrap');
  if (!boardOrNull || !boardWrapOrNull) throw new Error('languageSelect: board not found');
  const board: HTMLElement = boardOrNull;
  const boardWrap: HTMLElement = boardWrapOrNull;

  const grid = buildGrid();
  let settled = false;

  const colEls: HTMLElement[] = [];
  const cellEls: HTMLElement[][] = Array.from({ length: ROWS }, () => []);

  function paintCell(el: HTMLElement, cell: Cell) {
    if (cell.kind === 'filler') {
      el.style.background = FILLER_COLORS[cell.colorIdx];
      el.textContent = '';
    } else {
      el.style.background = LANG_COLOR[cell.lang];
      el.textContent = cell.text;
    }
  }

  for (let c = 0; c < COLS; c++) {
    const colEl = document.createElement('div');
    colEl.className = 'lang-col lang-col--vertical';
    for (let r = 0; r < ROWS; r++) {
      const cellEl = document.createElement('div');
      cellEl.className = 'lang-cell';
      paintCell(cellEl, grid[r][c]);
      colEl.appendChild(cellEl);
      cellEls[r][c] = cellEl;
    }
    board.appendChild(colEl);
    colEls[c] = colEl;
  }

  // Per-row hit target + arrow hint: separate absolutely-positioned overlay
  // elements, not extra in-flow flex children mixed in with the real cells —
  // an earlier horizontal version of this grid (the arrow-above-column
  // design) put the arrow as a real flex sibling *inside* the draggable
  // column, which silently shifted every cell's effective offset within
  // that column and threw off the ghost/wraparound fill math to look like
  // it was "routing around" the arrow. Keeping the hint entirely outside
  // the cell layout avoids that bug by construction.
  const rowHitEls: Record<number, HTMLElement> = {};
  const arrowEls: Record<number, HTMLElement> = {};
  const edgeArrowEls: Record<number, HTMLElement> = {};
  for (const dr of DRAG_ROWS) {
    const hit = document.createElement('div');
    hit.className = 'lang-row-hit';
    board.appendChild(hit);
    rowHitEls[dr] = hit;

    // Two hints per draggable row, exactly as the reference image marks
    // them: a solid arrowhead with a dashed tail sitting inside the grid at
    // the gap the travelling letter crosses, plus a double chevron parked
    // outside the board's right edge marking the whole row as draggable.
    // Each one's glyph lives in its own inner span so the nudge animation
    // owns `transform` outright — the outer element's transform is already
    // spent on centring it over its anchor point.
    const arrow = document.createElement('div');
    arrow.className = 'lang-row-arrow';
    arrow.innerHTML = `<span class="lang-arrow-nudge">${GAP_ARROW_SVG}</span>`;
    boardWrap.appendChild(arrow);
    arrowEls[dr] = arrow;

    const edge = document.createElement('div');
    edge.className = 'lang-row-edge-arrow';
    edge.innerHTML = `<span class="lang-arrow-nudge">${EDGE_CHEVRON_SVG}</span>`;
    boardWrap.appendChild(edge);
    edgeArrowEls[dr] = edge;
  }

  function layoutOverlays() {
    const boardRect = board.getBoundingClientRect();
    const wrapRect = boardWrap.getBoundingClientRect();
    // Everything sized off a tile (the letter, both arrow glyphs) reads this
    // one measured value, so the whole grid keeps the reference image's
    // proportions at any viewport size instead of drifting as a viewport
    // unit would.
    boardWrap.style.setProperty('--lang-cell-size', cellEls[0][0].getBoundingClientRect().width + 'px');

    for (const dr of DRAG_ROWS) {
      const cellRect = cellEls[dr][0].getBoundingClientRect();
      const hit = rowHitEls[dr];
      hit.style.left = '0px';
      hit.style.width = boardRect.width + 'px';
      hit.style.top = cellRect.top - boardRect.top + 'px';
      hit.style.height = cellRect.height + 'px';

      const cy = cellRect.top + cellRect.height / 2;
      // Both anchor points are a tile boundary, so all four arrows line up
      // on the same grid rhythm — gapAfter=-1 is column 0's left edge, the
      // rest are the midpoint of the gap they straddle.
      const gapAfter = DRAG_ROW_ARROW_GAP[dr];
      const anchorX =
        gapAfter < 0
          ? cellRect.left
          : (cellEls[dr][gapAfter].getBoundingClientRect().right +
              cellEls[dr][gapAfter + 1].getBoundingClientRect().left) /
            2;
      // Positioned relative to boardWrap (its actual offsetParent), not board.
      const arrow = arrowEls[dr];
      arrow.style.left = anchorX - wrapRect.left + 'px';
      arrow.style.top = cy - wrapRect.top + 'px';

      const edge = edgeArrowEls[dr];
      edge.style.left = boardRect.right - wrapRect.left + 10 + 'px';
      edge.style.top = cy - wrapRect.top + 'px';
    }
  }

  // Same pixel-based edge fade every other board's drag preview uses: a
  // ghost fully outside [low, high] is invisible, one just past the edge
  // ramps in over `range` instead of popping in at full ghost opacity.
  function edgeFade(x: number, low: number, high: number, range: number): number {
    const overshoot = x < low ? low - x : x > high ? x - high : 0;
    return Math.max(0, 1 - overshoot / range);
  }

  /** One dragged row's board-local geometry, in CSS pixels. */
  interface RowGeom {
    /** Each column's left offset inside the board. */
    xs: number[];
    y: number;
    w: number;
    h: number;
    /** Column pitch (tile width + gap) — one whole-slot shift. */
    step: number;
    /** Full wraparound period, i.e. the width of all 4 slots. */
    span: number;
  }

  // Captured once at pointer-down, while the row is still transform-free,
  // and then held constant for the whole drag. Re-measuring mid-drag would
  // read each tile's own live translateX back out of getBoundingClientRect
  // and fold it into the ghosts a second time — which is what the previous
  // version did, sending the wraparound tiles off at double the speed of the
  // row they belong to instead of trailing it in step.
  function measureRow(r: number): RowGeom {
    const boardRect = board.getBoundingClientRect();
    const rects = cellEls[r].map((el) => el.getBoundingClientRect());
    const xs = rects.map((rc) => rc.left - boardRect.left);
    const step = xs[1] - xs[0];
    return {
      xs,
      y: rects[0].top - boardRect.top,
      w: rects[0].width,
      h: rects[0].height,
      step,
      span: step * COLS,
    };
  }

  // Ghosts live directly on the board, not inside a single column: a column
  // is one tile wide, so a ghost parked there could only ever be positioned
  // against that column's own box — the previous version pinned every ghost
  // to `top: 0`, which is row 0, no matter which row was actually moving.
  function clearGhosts() {
    board.querySelectorAll('.lang-cell.ghost').forEach((g) => g.remove());
  }

  for (const r of DRAG_ROWS) {
    const hit = rowHitEls[r];
    let dx = 0;
    let geom: RowGeom | null = null;

    function renderDragPreview() {
      if (!geom) return;
      const g = geom;
      const magDx = magnetizeRawDist(dx / g.step) * g.step;
      for (let c = 0; c < COLS; c++) cellEls[r][c].style.transform = `translateX(${magDx}px)`;

      clearGhosts();
      // The same wraparound preview the square board uses: every tile is
      // redrawn one and two whole board-widths out to either side, so
      // whatever slides off one edge is already visibly on its way back in
      // at the other — same order, same spacing, just faded.
      const fadeRange = g.step * 0.4;
      for (let k = -2; k <= 2; k++) {
        if (k === 0) continue;
        for (let c = 0; c < COLS; c++) {
          const x = g.xs[c] + magDx + k * g.span;
          const fade = edgeFade(x, g.xs[0] - g.step, g.xs[0] + g.span, fadeRange);
          if (fade <= 0) continue;
          const ghost = document.createElement('div');
          ghost.className = 'lang-cell ghost';
          paintCell(ghost, grid[r][c]);
          ghost.style.left = x + 'px';
          ghost.style.top = g.y + 'px';
          ghost.style.width = g.w + 'px';
          ghost.style.height = g.h + 'px';
          ghost.style.opacity = String(0.55 * fade);
          board.appendChild(ghost);
        }
      }
    }

    function applyShift() {
      const g = geom;
      geom = null;
      clearGhosts();
      for (let c = 0; c < COLS; c++) cellEls[r][c].style.transform = '';
      if (!g) return;
      const shift = Math.round(dx / g.step);
      if (shift === 0) return;
      const n = COLS;
      const rowVals = grid[r].slice();
      const shifted = rowVals.map((_, i) => rowVals[(((i - shift) % n) + n) % n]);
      for (let c = 0; c < COLS; c++) {
        grid[r][c] = shifted[c];
        paintCell(cellEls[r][c], grid[r][c]);
      }
      vibrate(10);
      checkCompletion();
    }

    attachDrag(hit, {
      isActive: () => !settled,
      onStart() {
        dx = 0;
        for (let c = 0; c < COLS; c++) cellEls[r][c].style.transform = '';
        geom = measureRow(r);
        hit.classList.add('lang-row-hit--active');
      },
      onDrag(ddx) {
        dx = ddx;
        renderDragPreview();
      },
      onEnd(ddx) {
        dx = ddx;
        applyShift();
        hit.classList.remove('lang-row-hit--active');
      },
    });
  }

  function checkCompletion() {
    for (let c = 0; c < COLS; c++) {
      const word = COL_WORD[c];
      const start = COL_START[c];
      let ok = true;
      for (let i = 0; i < word.length; i++) {
        const cell = grid[start + i][c];
        if (cell.kind !== 'char' || cell.text !== word[i]) {
          ok = false;
          break;
        }
      }
      if (!ok) continue;
      settled = true;
      vibrate(24);
      const solvedEls: HTMLElement[] = [];
      for (let i = 0; i < word.length; i++) {
        const el = cellEls[start + i][c];
        el.classList.add('lang-cell--solving');
        solvedEls.push(el);
      }
      // A real score-style pulse (scale + glow, a couple of beats) plays out
      // before handing off — completing a word should read as a small win,
      // not an instant cut to the next screen.
      setTimeout(() => {
        for (const el of solvedEls) {
          el.classList.remove('lang-cell--solving');
          el.classList.add('lang-cell--solved');
        }
      }, 640);
      setTimeout(() => {
        teardown();
        onSelect(COL_LANG[c]);
      }, 900);
      return;
    }
  }

  layoutOverlays();
  const onResize = () => layoutOverlays();
  window.addEventListener('resize', onResize);

  // This screen is replaced wholesale by whatever comes next (main.ts swaps
  // #app's innerHTML), so it has to give back the two things that outlive
  // its own DOM: the scroll lock on <html>, and the resize listener that
  // would otherwise keep firing against detached cells forever.
  function teardown() {
    document.documentElement.classList.remove('lang-locked');
    window.removeEventListener('resize', onResize);
  }
}
